# Generated by Django 2.1 on 2021-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product1',
            name='summary',
        ),
        migrations.AlterField(
            model_name='product1',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
